/**
 * Gateway Bloque 1 copy defaults: P1, P2, P3, P4, Primera Verdad, Micro-espejo 1.
 * Extracted from: P1Cards.tsx, gateway-bloque1-data.ts
 */

import type { CopySection } from './types'

export function getGatewayBloque1Defaults(): CopySection[] {
  return [
    // ── P1 Role — Rol profesional (Hero) ────────────────────────────
    {
      id: 'gateway.p1role.question',
      section: 'gateway',
      subsection: 'p1role',
      label: 'Pregunta de rol',
      defaultValue: '¿Cuál describe mejor tu día a día?',
      fieldType: 'short',
      hint: 'Primera pregunta visual en el hero. 4 cards con ilustraciones.',
    },
    {
      id: 'gateway.p1role.leader',
      section: 'gateway',
      subsection: 'p1role',
      label: 'Rol — Líder',
      defaultValue: 'Lidero equipos',
      fieldType: 'short',
      hint: 'Card 1: directivos, managers, coordinadores.',
    },
    {
      id: 'gateway.p1role.entrepreneur',
      section: 'gateway',
      subsection: 'p1role',
      label: 'Rol — Emprendedor',
      defaultValue: 'Mi propio negocio',
      fieldType: 'short',
      hint: 'Card 2: autónomos, fundadores, freelance.',
    },
    {
      id: 'gateway.p1role.employee',
      section: 'gateway',
      subsection: 'p1role',
      label: 'Rol — Empleado',
      defaultValue: 'Trabajo para otros',
      fieldType: 'short',
      hint: 'Card 3: empleados, técnicos, consultores.',
    },
    {
      id: 'gateway.p1role.caregiver',
      section: 'gateway',
      subsection: 'p1role',
      label: 'Rol — Cuidador',
      defaultValue: 'Cuido o enseño',
      fieldType: 'short',
      hint: 'Card 4: sanitarios, docentes, terapeutas, cuidadores.',
    },

    // ── P1 — ¿Qué te trajo hasta aquí? ──────────────────────────────
    {
      id: 'gateway.p1.question',
      section: 'gateway',
      subsection: 'p1',
      label: 'Pregunta P1',
      defaultValue: '¿Qué te trajo hasta aquí?',
      fieldType: 'short',
      hint: 'Primera pregunta del gateway (después de seleccionar rol). Antes estaba en el hero.',
    },
    {
      id: 'gateway.p1.context',
      section: 'gateway',
      subsection: 'p1',
      label: 'P1 contexto',
      defaultValue: 'Esto no es una anzuelo. Lo que va a picar es la verdad.',
      fieldType: 'medium',
      hint: 'Texto de contexto bajo la pregunta P1.',
    },
    {
      id: 'gateway.p1.optionA.title',
      section: 'gateway',
      subsection: 'p1',
      label: 'P1 opción A — título',
      defaultValue: '\u201cNo logro entender mi malestar.\u201d',
      fieldType: 'short',
      hint: 'Primera opción de P1. Perfil: Productivo Colapsado.',
    },
    {
      id: 'gateway.p1.optionA.subtitle',
      section: 'gateway',
      subsection: 'p1',
      label: 'P1 opción A — subtítulo',
      defaultValue: 'Vas al médico, todo está bien. Pero tú no estás bien.',
      fieldType: 'medium',
      hint: 'Texto explicativo debajo de "Agotamiento que no se va".',
    },
    {
      id: 'gateway.p1.optionB.title',
      section: 'gateway',
      subsection: 'p1',
      label: 'P1 opción B — título',
      defaultValue: '\u201cEmpiezo a tener consecuencias serias.\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p1.optionB.subtitle',
      section: 'gateway',
      subsection: 'p1',
      label: 'P1 opción B — subtítulo',
      defaultValue: 'Tus relaciones personales, profesionales y tu salud van en picado.',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p1.optionC.title',
      section: 'gateway',
      subsection: 'p1',
      label: 'P1 opción C — título',
      defaultValue: 'Me siento atrapado en mi propia vida.',
      fieldType: 'short',
    },
    {
      id: 'gateway.p1.optionC.subtitle',
      section: 'gateway',
      subsection: 'p1',
      label: 'P1 opción C — subtítulo',
      defaultValue: 'Tu profesión y tu vida han dejado de ilusionarte.',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p1.optionD.title',
      section: 'gateway',
      subsection: 'p1',
      label: 'P1 opción D — título',
      defaultValue: 'Agotamiento crónico.',
      fieldType: 'short',
    },
    {
      id: 'gateway.p1.optionD.subtitle',
      section: 'gateway',
      subsection: 'p1',
      label: 'P1 opción D — subtítulo',
      defaultValue: 'Duermes y amaneces igual de vacío. El cuerpo ya no se recupera.',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p1.optionE.title',
      section: 'gateway',
      subsection: 'p1',
      label: 'P1 opción E — título',
      defaultValue: 'Mi mente vive en alerta máxima.',
      fieldType: 'short',
    },
    {
      id: 'gateway.p1.optionE.subtitle',
      section: 'gateway',
      subsection: 'p1',
      label: 'P1 opción E — subtítulo',
      defaultValue: 'Vives con miedo a perder todo lo que te importa.',
      fieldType: 'medium',
    },

    // ── P2 — Sueño ──────────────────────────────────────────────────
    {
      id: 'gateway.p2.optionA',
      section: 'gateway',
      subsection: 'p2',
      label: 'P2 opción A — mente no se apaga',
      defaultValue: '\u201cMe cuesta dormirme — mi mente no se apaga\u201d',
      fieldType: 'short',
      hint: 'Opciones de sueño. Cada opción aparece como card seleccionable.',
    },
    {
      id: 'gateway.p2.optionB',
      section: 'gateway',
      subsection: 'p2',
      label: 'P2 opción B — despertar nocturno',
      defaultValue: '\u201cMe despierto a las 3-4 de la mañana y no puedo volver a dormirme\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p2.optionC',
      section: 'gateway',
      subsection: 'p2',
      label: 'P2 opción C — sueño no reparador',
      defaultValue: '\u201cDuermo horas pero me despierto igual de cansado\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p2.optionD',
      section: 'gateway',
      subsection: 'p2',
      label: 'P2 opción D — poco sueño funcional',
      defaultValue: '\u201cDuermo poco pero funciono\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p2.optionE',
      section: 'gateway',
      subsection: 'p2',
      label: 'P2 opción E — sueño bueno',
      defaultValue: '\u201cMi sueño es razonablemente bueno\u201d',
      fieldType: 'short',
    },

    // ── P3 — Síntomas cognitivos (selección múltiple) ────────────────
    {
      id: 'gateway.p3.niebla.title',
      section: 'gateway',
      subsection: 'p3',
      label: 'P3 — Niebla mental (título)',
      defaultValue: 'Saturación mental',
      fieldType: 'short',
      hint: 'P3 es selección múltiple. Cada opción tiene título + subtítulo.',
    },
    {
      id: 'gateway.p3.niebla.subtitle',
      section: 'gateway',
      subsection: 'p3',
      label: 'P3 — Niebla mental (subtítulo)',
      defaultValue: 'Leo algo y al terminar no sé ni qué he leído.',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p3.decisiones.title',
      section: 'gateway',
      subsection: 'p3',
      label: 'P3 — Peores decisiones (título)',
      defaultValue: 'Me cuesta concentrarme y tomar buenas decisiones',
      fieldType: 'short',
    },
    {
      id: 'gateway.p3.decisiones.subtitle',
      section: 'gateway',
      subsection: 'p3',
      label: 'P3 — Peores decisiones (subtítulo)',
      defaultValue: 'He perdido capacidad y claridad mental. Decisiones simples se vuelven agotadoras.',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p3.dispersa.title',
      section: 'gateway',
      subsection: 'p3',
      label: 'P3 — Mente dispersa (título)',
      defaultValue: 'Falta de foco',
      fieldType: 'short',
    },
    {
      id: 'gateway.p3.dispersa.subtitle',
      section: 'gateway',
      subsection: 'p3',
      label: 'P3 — Mente dispersa (subtítulo)',
      defaultValue: 'Mi cabeza salta de un tema a otro sin control',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p3.palabras.title',
      section: 'gateway',
      subsection: 'p3',
      label: 'P3 — Palabras perdidas (título)',
      defaultValue: 'No me viene la palabra',
      fieldType: 'short',
    },
    {
      id: 'gateway.p3.palabras.subtitle',
      section: 'gateway',
      subsection: 'p3',
      label: 'P3 — Palabras perdidas (subtítulo)',
      defaultValue: 'Últimamente me cuesta recordar la palabra que busco.',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p3.decisional.title',
      section: 'gateway',
      subsection: 'p3',
      label: 'P3 — Agotamiento decisional (título)',
      defaultValue: '\u201cAgotamiento decisional\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p3.decisional.subtitle',
      section: 'gateway',
      subsection: 'p3',
      label: 'P3 — Agotamiento decisional (subtítulo)',
      defaultValue: 'Al final del día no puedo elegir ni qué cenar.',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p3.ninguna.title',
      section: 'gateway',
      subsection: 'p3',
      label: 'P3 — Ninguna de estas',
      defaultValue: '\u201cNinguna de estas\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p3.ninguna.subtitle',
      section: 'gateway',
      subsection: 'p3',
      label: 'P3 — Ninguna de estas (subtítulo)',
      defaultValue: '',
      fieldType: 'short',
    },

    // ── P4 — Síntomas emocionales ────────────────────────────────────
    {
      id: 'gateway.p4.optionA.title',
      section: 'gateway',
      subsection: 'p4',
      label: 'P4 — Irritabilidad (título)',
      defaultValue: '\u201cIrritabilidad\u201d',
      fieldType: 'short',
      hint: 'Opciones emocionales. Cada una con título + subtítulo explicativo.',
    },
    {
      id: 'gateway.p4.optionA.subtitle',
      section: 'gateway',
      subsection: 'p4',
      label: 'P4 — Irritabilidad (subtítulo)',
      defaultValue: 'Reaccionas a menudo con enfado con impaciencia.',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p4.optionB.title',
      section: 'gateway',
      subsection: 'p4',
      label: 'P4 — Vacío (título)',
      defaultValue: '\u201cNo logro disfrutar con nada.\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p4.optionB.subtitle',
      section: 'gateway',
      subsection: 'p4',
      label: 'P4 — Vacío (subtítulo)',
      defaultValue: 'Lo que te hacía feliz ya no te satisface.',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p4.optionC.title',
      section: 'gateway',
      subsection: 'p4',
      label: 'P4 — Explosiones de culpa (título)',
      defaultValue: '\u201cReaccionas por detalles insignificantes\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p4.optionC.subtitle',
      section: 'gateway',
      subsection: 'p4',
      label: 'P4 — Explosiones de culpa (subtítulo)',
      defaultValue: 'Explotas con quien más quieres y después te sientes fatal.',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p4.optionD.title',
      section: 'gateway',
      subsection: 'p4',
      label: 'P4 — Anestesia emocional (título)',
      defaultValue: '\u201cVivo desconectado de mí y de los demás\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p4.optionD.subtitle',
      section: 'gateway',
      subsection: 'p4',
      label: 'P4 — Anestesia emocional (subtítulo)',
      defaultValue: 'Tiendes a aislarte y no te apetece relacionarte.',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p4.optionE.title',
      section: 'gateway',
      subsection: 'p4',
      label: 'P4 — Obsesividad mental (título)',
      defaultValue: '\u201cObsesividad mental\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p4.optionE.subtitle',
      section: 'gateway',
      subsection: 'p4',
      label: 'P4 — Obsesividad mental (subtítulo)',
      defaultValue: 'Mi mente me pide estimulación constante y no puedo pararla.',
      fieldType: 'medium',
    },
    {
      id: 'gateway.p4.optionF.title',
      section: 'gateway',
      subsection: 'p4',
      label: 'P4 — Razonablemente bien (título)',
      defaultValue: '\u201cRazonablemente bien\u201d',
      fieldType: 'short',
    },
    {
      id: 'gateway.p4.optionF.subtitle',
      section: 'gateway',
      subsection: 'p4',
      label: 'P4 — Razonablemente bien (subtítulo)',
      defaultValue: 'Tu equilibrio emocional es aceptable.',
      fieldType: 'medium',
    },

    // ── PRIMERA VERDAD — combinaciones P1×P2 ─────────────────────────
    {
      id: 'gateway.primeraverdad.AA.text',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad A-A — texto',
      defaultValue: 'Tu mente no se apaga ya que el estrés crónico promociona hormonas como la adrenalina, la noradrenalina y el cortisol que promueven la activación de modo huída. Esta respuesta recluta recursos energéticos que no se gastan físicamente (ciclo del estrés incompleto). Tu cuerpo usa esa energía en procesos obsesivos compulsivos negativos que retroalimentan el modo simpático.',
      fieldType: 'long',
      hint: 'Combinación: Agotamiento + Mente no se apaga. Texto personalizado de reflexión.',
    },
    {
      id: 'gateway.primeraverdad.AA.collective',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad A-A — dato colectivo',
      defaultValue: 'El 78% de los +25.000 sistemas nerviosos analizados no está ajustado ni a los ciclos ni a los biorritmos que tu cuerpo necesita para funcionar de forma equilibrada.',
      fieldType: 'long',
      hint: 'Dato colectivo que aparece debajo del texto de la Primera Verdad.',
    },
    {
      id: 'gateway.primeraverdad.AB.text',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad A-B — texto',
      defaultValue: 'A nivel bioquímico este patrón suele conectarse con la hipoglucemia nocturna. Tu cuerpo no tiene la energía suficiente para completar los ciclos de sueño y segrega hormonas que promocionan energía rápida pero activan tu sistema nervioso. Normalmente es un síntoma fácil y rápido de regular.',
      fieldType: 'long',
      hint: 'Combinación: Agotamiento + Despertar nocturno.',
    },
    {
      id: 'gateway.primeraverdad.AB.collective',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad A-B — dato colectivo',
      defaultValue: 'El 82% de las personas que hemos neuroregulado responden en menos de 72 h a protocolos de suplementación con aminoácidos que estabilizan el metabolismo energético incrementando drásticamente la calidad y cantidad de su descanso.',
      fieldType: 'long',
    },
    {
      id: 'gateway.primeraverdad.BA.text',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad B-A — texto',
      defaultValue: 'Tu rendimiento bajó porque has estado expuesto a niveles de estrés muy altos que han comprometido tu descanso. La falta de sueño te ha llevado a un estado de mayor irritabilidad, reactividad y negatividad.',
      fieldType: 'long',
      hint: 'Combinación: Rendimiento en caída + Mente no se apaga.',
    },
    {
      id: 'gateway.primeraverdad.BA.collective',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad B-A — dato colectivo',
      defaultValue: 'El 71% de ejecutivos con deterioro cognitivo progresivo reportan un patrón de sueño idéntico al tuyo como factor previo. La conexión es directa y reversible.',
      fieldType: 'long',
    },
    {
      id: 'gateway.primeraverdad.CB.text',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad C-B — texto',
      defaultValue: 'Este síntoma puede estar relacionado con una déficit metabólico o con deficiencias en los neurotransmisores y hormonas que regulan los ciclos de sueño y vigilia.',
      fieldType: 'long',
      hint: 'Combinación: El cuerpo habla + Despertar nocturno.',
    },
    {
      id: 'gateway.primeraverdad.CB.collective',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad C-B — dato colectivo',
      defaultValue: 'El 82% de las personas con señales físicas persistentes y sueño no reparador muestran activación crónica del sistema de alerta. Vivir en modo huida compromete seriamente tu salud física y emocional. Tus relaciones y tus logros se ponen en riesgo.',
      fieldType: 'long',
    },
    {
      id: 'gateway.primeraverdad.CC.text',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad C-C — texto',
      defaultValue: 'Tu cuerpo te está dando señales que tu mente intenta ignorar. El cansancio que no se va con sueño es la más clara — y la que más información contiene.',
      fieldType: 'long',
      hint: 'Combinación: El cuerpo habla + Sueño no reparador.',
    },
    {
      id: 'gateway.primeraverdad.CC.collective',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad C-C — dato colectivo',
      defaultValue: 'El 82% de las personas con señales físicas persistentes y sueño no reparador muestran activación crónica del sistema de alerta. Vivir en modo huida compromete seriamente tu salud física y emocional. Tus relaciones y tus logros se ponen en riesgo.',
      fieldType: 'long',
    },
    {
      id: 'gateway.primeraverdad.D.text',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad D (derivado) — texto',
      defaultValue: 'La gente que tienes cerca puede ver claramente las consecuencias para ti y para los demás del comportamiento que tú llevas tiempo normalizando. Tu sistema nervioso te empieza a dar señales de alarma.',
      fieldType: 'long',
      hint: 'Para P1=D (Alguien me lo sugirió). Independiente de P2.',
    },
    {
      id: 'gateway.primeraverdad.D.collective',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad D — dato colectivo',
      defaultValue: 'El 69% de personas derivadas por un profesional presentan un nivel de agotamiento que ya habían normalizado completamente.',
      fieldType: 'long',
    },
    {
      id: 'gateway.primeraverdad.ED.text',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad E-D — texto',
      defaultValue: 'Dices que funcionas con poco sueño. Las ciencia es clara y contundente: este comportamiento implica grandes riesgos para la salud como la neurodegeneración y el riesgo cardiovascular.',
      fieldType: 'long',
      hint: 'Combinación: Curiosidad + Duermo poco pero funciono.',
    },
    {
      id: 'gateway.primeraverdad.ED.collective',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad E-D — dato colectivo',
      defaultValue: 'El 74% de personas que declaran "funcionar con poco sueño" muestran marcadores de déficit cognitivo acumulado que no perciben. El umbral se mueve — lo que antes era cansancio ya no lo registras como tal.',
      fieldType: 'long',
    },
    {
      id: 'gateway.primeraverdad.default.text',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad — fallback por defecto',
      defaultValue: 'Tu sistema nervioso lleva tiempo funcionando en modo de emergencia. Lo que sientes no es debilidad — es el resultado predecible de un sistema que no ha descansado de verdad.',
      fieldType: 'long',
      hint: 'Se usa cuando la combinación P1×P2 no tiene texto específico.',
    },
    {
      id: 'gateway.primeraverdad.default.collective',
      section: 'gateway',
      subsection: 'primeraverdad',
      label: 'Primera Verdad — dato colectivo fallback',
      defaultValue: 'El 78% de los +25.000 sistemas nerviosos que hemos analizados con tu patrón de respuestas presentan niveles elevados de cortisol y adrenalina, provocando estrés crónico e inflamación sistémica.',
      fieldType: 'long',
    },

    // ── MICRO-ESPEJO 1 — variantes P3×P4 ─────────────────────────────
    {
      id: 'gateway.microespejo1.pocoB.text',
      section: 'gateway',
      subsection: 'microespejo1',
      label: 'Micro-espejo 1 — pocos síntomas + Vacío',
      defaultValue: 'Tu cerebro funciona pero por dentro hay un vacío. No es tristeza — es un sistema nervioso que se ha apagado para protegerte. Como un fusible que salta.',
      fieldType: 'long',
      hint: 'Pocas señales cognitivas + P4=Vacío. Texto de reflexión personalizado.',
    },
    {
      id: 'gateway.microespejo1.pocoB.collective',
      section: 'gateway',
      subsection: 'microespejo1',
      label: 'Micro-espejo 1 — pocoB dato colectivo',
      defaultValue: 'El 68% de personas con tu combinación no identifican esto como agotamiento. Lo viven como ausencia sin causa. Tiene causa — y tiene solución.',
      fieldType: 'long',
    },
    {
      id: 'gateway.microespejo1.muchoC.text',
      section: 'gateway',
      subsection: 'microespejo1',
      label: 'Micro-espejo 1 — muchos síntomas + Explosiones',
      defaultValue: 'Das todo lo que tienes a los demás y lo que queda para ti no es suficiente. Tu cerebro no tiene recursos para regularse  y el resultado es que explotas con quien más aprecias.',
      fieldType: 'long',
      hint: 'Muchas señales cognitivas + P4=Explosiones de culpa.',
    },
    {
      id: 'gateway.microespejo1.muchoC.collective',
      section: 'gateway',
      subsection: 'microespejo1',
      label: 'Micro-espejo 1 — muchoC dato colectivo',
      defaultValue: 'El 79% de personas con tu patrón sienten culpa después de las explosiones. Esa culpa también agota. Es un ciclo — no un defecto de carácter.',
      fieldType: 'long',
    },
    {
      id: 'gateway.microespejo1.muchoD.text',
      section: 'gateway',
      subsection: 'microespejo1',
      label: 'Micro-espejo 1 — muchos síntomas + Anestesia',
      defaultValue: 'Tu cuerpo ha encontrado la forma más radical de protegerte: apagar los circuitos. No es que no te importe — es que sentir se volvió demasiado costoso para tu sistema.',
      fieldType: 'long',
      hint: 'Muchas señales cognitivas + P4=Anestesia emocional.',
    },
    {
      id: 'gateway.microespejo1.muchoD.collective',
      section: 'gateway',
      subsection: 'microespejo1',
      label: 'Micro-espejo 1 — muchoD dato colectivo',
      defaultValue: 'El 74% de personas con anestesia emocional tardan más de 2 años en identificar lo que les ocurre. Tú lo estás nombrando hoy.',
      fieldType: 'long',
    },
    {
      id: 'gateway.microespejo1.pocoE.text',
      section: 'gateway',
      subsection: 'microespejo1',
      label: 'Micro-espejo 1 — pocos síntomas + Obsesividad mental',
      defaultValue: 'Tu capacidad cognitiva está intacta pero tu mente la usa para anticipar en lugar de ejecutar. No estás pensando — estás sobreviviendo mentalmente.',
      fieldType: 'long',
      hint: 'Pocas señales cognitivas + P4=Obsesividad mental.',
    },
    {
      id: 'gateway.microespejo1.pocoE.collective',
      section: 'gateway',
      subsection: 'microespejo1',
      label: 'Micro-espejo 1 — pocoE dato colectivo',
      defaultValue: 'El 73% de personas con obsesividad mental activa tienen el sistema nervioso en hipervigilancia constante. La amenaza que tratas de predecir agotan tus recursos energéticos y comprometen tu bienestar emocional, tu claridad mental, la creatividad y la agilidad para hacer frente tanto a los imprevistos .',
      fieldType: 'long',
    },
    {
      id: 'gateway.microespejo1.default.text',
      section: 'gateway',
      subsection: 'microespejo1',
      label: 'Micro-espejo 1 — fallback',
      defaultValue: 'Tu cabeza va a mil pero tu capacidad de procesar la información se ha reducido de forma dramática. No logras ni desconectar ni descansar y te sientes frustrado, asustado y desorientado con esta situación.',
      fieldType: 'long',
      hint: 'Se usa cuando la combinación P3×P4 no tiene variante específica.',
    },
    {
      id: 'gateway.microespejo1.default.collective',
      section: 'gateway',
      subsection: 'microespejo1',
      label: 'Micro-espejo 1 — fallback dato colectivo',
      defaultValue: 'El 65% de personas con tu combinación de respuestas no saben que la irritabilidad y la saturación cognitiva tienen la misma causa. Cuando se regula una, la otra mejora.',
      fieldType: 'long',
    },
  ]
}
