/**
 * Landing page copy defaults.
 * Extracted from: HeroSection, MirrorSection, TensionSection,
 * SocialProofSection, ReliefSection, Footer.
 */

import type { CopySection } from './types'

export function getLandingDefaults(): CopySection[] {
  return [
    // ── HERO ──────────────────────────────────────────────────────────
    {
      id: 'hero.shock',
      section: 'landing',
      subsection: 'hero',
      label: 'Frase shock inicial',
      defaultValue: 'Hemos analizado +25.000 sistemas nerviosos y regulado a miles de personas.',
      fieldType: 'medium',
      hint: 'Primera frase que ve la persona. Aparece en cursiva sobre el hero, antes de todo.',
    },
    {
      id: 'hero.headline',
      section: 'landing',
      subsection: 'hero',
      label: 'Titular principal del hero',
      defaultValue: 'Gratis. Confidencial. Incómodo. El mapa de tu sistema nervioso en menos de 3 minutos.',
      fieldType: 'short',
      hint: 'Título grande y en negrita. Es lo que más destaca en la pantalla inicial.',
    },
    {
      id: 'hero.subtitle',
      section: 'landing',
      subsection: 'hero',
      label: 'Subtítulo del hero',
      defaultValue: 'Esto no es una anzuelo. Lo que va a picar es la verdad.',
      fieldType: 'medium',
      hint: 'Texto explicativo debajo del titular. Describe qué va a hacer la persona.',
    },
    {
      id: 'hero.micropromises',
      section: 'landing',
      subsection: 'hero',
      label: 'Micro-promesas',
      defaultValue: '10 preguntas\u00a0·\u00a03 minutos\u00a0·\u00a0Sin registro previo',
      fieldType: 'short',
      hint: 'Línea pequeña debajo de las cards de P1. Reduce fricción.',
    },

    // ── ESPEJO (Mirror) ───────────────────────────────────────────────
    {
      id: 'mirror.overline',
      section: 'landing',
      subsection: 'mirror',
      label: 'Overline de la sección espejo',
      defaultValue: 'LO QUE SIENTES TIENE NOMBRE',
      fieldType: 'short',
      hint: 'Texto pequeño en mayúsculas encima del titular. Marca el inicio de la sección.',
    },
    {
      id: 'mirror.headline',
      section: 'landing',
      subsection: 'mirror',
      label: 'Titular de la sección espejo',
      defaultValue: 'Y tiene solución.',
      fieldType: 'short',
      hint: 'Título grande de la sección de normalización. Reframe emocional.',
    },
    {
      id: 'mirror.impact',
      section: 'landing',
      subsection: 'mirror',
      label: 'Frase de impacto aislada',
      defaultValue: 'Tus síntomas no son el enemigo. Son lo más honesto que tienes.',
      fieldType: 'short',
      hint: 'Frase corta en cursiva. Aparece sola, en grande, justo después del titular.',
    },
    {
      id: 'mirror.body1',
      section: 'landing',
      subsection: 'mirror',
      label: 'Párrafo 1 — explicación',
      defaultValue: 'El sueño roto, la cabeza que no para, la paciencia que se agota a media mañana... Eso no es debilidad. Es la sabiduría de un cuerpo que se niega a seguir sosteniendo una vida que te está destruyendo. Y no, la solución no empieza hablando de tus emociones. Empieza en un laboratorio.',
      fieldType: 'long',
      hint: 'Primer párrafo explicativo. Conecta los síntomas con la causa biológica.',
    },
    {
      id: 'mirror.body2',
      section: 'landing',
      subsection: 'mirror',
      label: 'Párrafo 2 — reframe biológico',
      defaultValue: 'Porque cuando tu cortisol está disparado y tus neurotransmisores están por el suelo, ninguna sesión de coaching te va a devolver la claridad. Es como pedirle a alguien que piense mejor con fiebre de 40.',
      fieldType: 'medium',
      hint: 'Segundo párrafo. Normaliza: no eres tú, es tu biología.',
    },
    {
      id: 'mirror.pullquote',
      section: 'landing',
      subsection: 'mirror',
      label: 'Cita destacada del espejo',
      defaultValue: 'Primero se repara la bioquímica. Después — y solo después — se toca la psicología. Saltarse ese orden es la razón por la que llevas años probando cosas que no funcionan.',
      fieldType: 'short',
      hint: 'Frase en color acento con borde lateral. Cierre emocional de la sección.',
    },

    // ── TENSIÓN ───────────────────────────────────────────────────────
    {
      id: 'tension.overline',
      section: 'landing',
      subsection: 'tension',
      label: 'Overline de tensión',
      defaultValue: 'EL COSTE DE NO SABER',
      fieldType: 'short',
      hint: 'Texto en mayúsculas que encabeza las 3 cards de estadísticas.',
    },
    {
      id: 'tension.card1.number',
      section: 'landing',
      subsection: 'tension',
      label: 'Card terracota — número',
      defaultValue: '73%',
      fieldType: 'short',
      hint: 'Número grande animado de la primera card (fondo terracota).',
    },
    {
      id: 'tension.card1.title',
      section: 'landing',
      subsection: 'tension',
      label: 'Card terracota — título',
      defaultValue: 'de ejecutivos con burnout no lo saben.',
      fieldType: 'short',
      hint: 'Frase que acompaña al 73%. Aparece justo debajo del número.',
    },
    {
      id: 'tension.card1.body',
      section: 'landing',
      subsection: 'tension',
      label: 'Card terracota — texto',
      defaultValue: 'Confunden el agotamiento con \u201cuna mala racha\u201d y pierden meses — a veces años — mientras su biología se deteriora.',
      fieldType: 'medium',
      hint: 'Explicación debajo del título en la card terracota.',
    },
    {
      id: 'tension.card2.number',
      section: 'landing',
      subsection: 'tension',
      label: 'Card marrón — número',
      defaultValue: '12-15h',
      fieldType: 'short',
      hint: 'Número grande animado de la segunda card (fondo marrón).',
    },
    {
      id: 'tension.card2.title',
      section: 'landing',
      subsection: 'tension',
      label: 'Card marrón — título',
      defaultValue: 'semanales de rendimiento real perdidas.',
      fieldType: 'short',
      hint: 'Frase que acompaña al 12-15h.',
    },
    {
      id: 'tension.card2.body',
      section: 'landing',
      subsection: 'tension',
      label: 'Card marrón — texto',
      defaultValue: 'No en tiempo — en calidad de decisiones, en paciencia, en energía para lo que importa.',
      fieldType: 'medium',
      hint: 'Explicación debajo del título en la card marrón.',
    },
    {
      id: 'tension.card3.title',
      section: 'landing',
      subsection: 'tension',
      label: 'Card blanca — titular',
      defaultValue: 'El burnout no se arregla con vacaciones.',
      fieldType: 'short',
      hint: 'Titular en negrita de la card blanca con badge "DATO CLAVE".',
    },
    {
      id: 'tension.card3.body',
      section: 'landing',
      subsection: 'tension',
      label: 'Card blanca — texto',
      defaultValue: 'Si tu cortisol no baja, tu sueño no se repara y tu sistema no se regula, dos semanas en la playa son un parche. Vuelves y en 72 horas estás igual.',
      fieldType: 'long',
      hint: 'Explicación de la card blanca. Desmonta la idea de que vacaciones = solución.',
    },

    // ── PRUEBA SOCIAL ─────────────────────────────────────────────────
    {
      id: 'socialproof.overline',
      section: 'landing',
      subsection: 'socialproof',
      label: 'Overline de testimonios',
      defaultValue: 'EXPERIENCIAS REALES',
      fieldType: 'short',
      hint: 'Texto en mayúsculas encima de los testimonios.',
    },
    {
      id: 'socialproof.headline',
      section: 'landing',
      subsection: 'socialproof',
      label: 'Titular de testimonios',
      defaultValue: 'Lo que dicen quienes ya pasaron por aquí.',
      fieldType: 'short',
      hint: 'Título grande de la sección de testimonios.',
    },
    {
      id: 'socialproof.t1.quote',
      section: 'landing',
      subsection: 'socialproof',
      label: 'Testimonio 1 — cita',
      defaultValue: 'Creía que necesitaba más disciplina. En 3 minutos descubrí que necesitaba regulación.',
      fieldType: 'medium',
      hint: 'Primer testimonio (card lavanda). Perfil: Productivo Colapsado.',
    },
    {
      id: 'socialproof.t1.author',
      section: 'landing',
      subsection: 'socialproof',
      label: 'Testimonio 1 — autor',
      defaultValue: 'Director de operaciones, 47',
      fieldType: 'short',
      hint: 'Descripción del autor del primer testimonio. No usar nombre real.',
    },
    {
      id: 'socialproof.t2.quote',
      section: 'landing',
      subsection: 'socialproof',
      label: 'Testimonio 2 — cita',
      defaultValue: 'No le conté a nadie que lo hice. Los datos me explicaron lo que yo no quería ver.',
      fieldType: 'medium',
      hint: 'Segundo testimonio (card crema). Perfil: Fuerte Invisible.',
    },
    {
      id: 'socialproof.t2.author',
      section: 'landing',
      subsection: 'socialproof',
      label: 'Testimonio 2 — autor',
      defaultValue: 'CEO, 52',
      fieldType: 'short',
      hint: 'Descripción del autor del segundo testimonio.',
    },
    {
      id: 'socialproof.t3.quote',
      section: 'landing',
      subsection: 'socialproof',
      label: 'Testimonio 3 — cita',
      defaultValue: 'Lo hice por curiosidad científica. Los resultados me desarmaron.',
      fieldType: 'medium',
      hint: 'Tercer testimonio (card lima). Perfil: Controlador Paralizado.',
    },
    {
      id: 'socialproof.t3.author',
      section: 'landing',
      subsection: 'socialproof',
      label: 'Testimonio 3 — autor',
      defaultValue: 'Socia fundadora, 39',
      fieldType: 'short',
      hint: 'Descripción del autor del tercer testimonio.',
    },

    // ── ALIVIO (Relief) ───────────────────────────────────────────────
    {
      id: 'relief.overline',
      section: 'landing',
      subsection: 'relief',
      label: 'Overline del análisis',
      defaultValue: 'EL ANÁLISIS',
      fieldType: 'short',
      hint: 'Texto en mayúsculas que encabeza la sección final.',
    },
    {
      id: 'relief.headline',
      section: 'landing',
      subsection: 'relief',
      label: 'Titular del análisis',
      defaultValue: 'Tu empresa tiene KPIs para todo. Tu sistema nervioso no tiene ni uno. Hasta ahora.',
      fieldType: 'medium',
      hint: 'Título grande de la sección de alivio/CTA final.',
    },
    {
      id: 'relief.description',
      section: 'landing',
      subsection: 'relief',
      label: 'Descripción del análisis',
      defaultValue: 'Cuando termines, recibirás el mapa único de tu sistema nervioso: una puntuación global de 0 a 100 y cinco dimensiones desglosadas. Regulación nerviosa, calidad de sueño, claridad cognitiva, equilibrio emocional y alegría de vivir, cada una con su valor. Eso es la puerta. Lo que hay detrás lo vamos abriendo juntos, capa a capa, cada pocos días.',
      fieldType: 'long',
      hint: 'Párrafo que explica qué hace el análisis. Debajo del titular.',
    },
    {
      id: 'relief.credential.harvard',
      section: 'landing',
      subsection: 'relief',
      label: 'Credencial — Harvard',
      defaultValue: 'Médico Funcional  Psicoterapéuta',
      fieldType: 'short',
      hint: 'Etiqueta de la credencial universitaria junto a la foto del doctor.',
    },
    {
      id: 'relief.credential.doctor',
      section: 'landing',
      subsection: 'relief',
      label: 'Credencial — nombre del doctor',
      defaultValue: 'Dr. Carlos Alvear López',
      fieldType: 'short',
      hint: 'Nombre del doctor que aparece junto a su foto.',
    },
    {
      id: 'relief.credential.analyzed',
      section: 'landing',
      subsection: 'relief',
      label: 'Credencial — sistemas analizados',
      defaultValue: 'Sistemas nerviosos analizados',
      fieldType: 'short',
      hint: 'Texto debajo del número +25.000 en la card de credenciales.',
    },
    {
      id: 'relief.credential.years',
      section: 'landing',
      subsection: 'relief',
      label: 'Credencial — años de práctica',
      defaultValue: 'Años de práctica médica',
      fieldType: 'short',
      hint: 'Texto debajo del número +20 en la card de credenciales.',
    },
    {
      id: 'relief.collective',
      section: 'landing',
      subsection: 'relief',
      label: 'Dato colectivo semanal',
      defaultValue: '{{count}} personas completaron este análisis esta semana.',
      fieldType: 'short',
      hint: 'Texto con contador animado. {{count}} se reemplaza por el número real.',
    },
    {
      id: 'relief.cta',
      section: 'landing',
      subsection: 'relief',
      label: 'Botón CTA final',
      defaultValue: 'Empezar mi análisis →',
      fieldType: 'short',
      hint: 'Texto del botón verde lima que lleva al inicio del gateway.',
    },
    {
      id: 'relief.friction',
      section: 'landing',
      subsection: 'relief',
      label: 'Texto de fricción',
      defaultValue: 'Tu resultado es confidencial. No compartimos datos con terceros.',
      fieldType: 'short',
      hint: 'Texto pequeño debajo del CTA. Disuelve miedo a privacidad.',
    },

    // ── FOOTER ────────────────────────────────────────────────────────
    {
      id: 'footer.copyright',
      section: 'landing',
      subsection: 'footer',
      label: 'Copyright del footer',
      defaultValue: '© 2026 Instituto Epigenético. Todos los derechos reservados.',
      fieldType: 'short',
      hint: 'Línea de copyright al final de la página.',
    },
  ]
}
